name=BLSD20Modbus
version=0.1.0
author=brendlij
maintainer=brendlij
sentence=Arduino library for Smart Motor Devices BLSD-20Modbus.
paragraph=Lightweight object-oriented library for controlling BLSD-20Modbus motor controllers over Modbus RTU.
category=Device Control
architectures=*